apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: default
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  JWT_ISSUER: "U_VoluntApp_Backend.Src"
  JWT_AUDIENCE: "UVoluntapp.Client"
  JWT_EXPIRY_MINUTES: "60"
  ENABLE_HTTPS_REDIRECTION: "false"
  CORS_ALLOWED_ORIGINS: "*"