// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using U_VoluntApp_Core.Src.Infrastructure.Persistence;

#nullable disable

namespace U_VoluntApp_Core.Src.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Activity.Activity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActivityTypeCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("activity_type_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<double>("LocationLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("location_latitude");

                    b.Property<double>("LocationLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("location_longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ProgramCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("program_code");

                    b.Property<int>("RegistrationRadiusMeters")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(50)
                        .HasColumnName("registration_radius_meters");

                    b.Property<string>("ResponsibleProfileCode")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("responsible_profile_code");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("stage-1")
                        .HasColumnName("state_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UvaCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uva_code");

                    b.Property<string>("VolProgramPatternCode")
                        .HasColumnType("text")
                        .HasColumnName("vol_program_pattern_code");

                    b.HasKey("Id")
                        .HasName("activities_pkey");

                    b.HasIndex("ProgramCode");

                    b.HasIndex("ResponsibleProfileCode");

                    b.HasIndex("UvaCode")
                        .IsUnique();

                    b.HasIndex("VolProgramPatternCode");

                    b.ToTable("activities", (string)null);
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Activity.ActivityGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActivityCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("activity_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("stage-1")
                        .HasColumnName("state_code");

                    b.Property<int?>("TotalCapacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_capacity");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UvaCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uva_code");

                    b.HasKey("Id")
                        .HasName("activity_group_pkey");

                    b.HasIndex("ActivityCode");

                    b.HasIndex("UvaCode")
                        .IsUnique();

                    b.ToTable("activity_group", (string)null);
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Activity.ActivityRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActivityCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("activity_code");

                    b.Property<decimal>("CostAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("cost_amount");

                    b.Property<bool>("CountsVolunteerHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("counts_volunteer_hours");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("EnrollmentDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrollment_deadline");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<bool>("RequiresApproval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("requires_approval");

                    b.Property<bool>("RequiresEnrollment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("requires_enrollment");

                    b.Property<int?>("TotalCapacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_capacity");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UvaCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uva_code");

                    b.HasKey("Id")
                        .HasName("activity_rules_pkey");

                    b.HasIndex("UvaCode")
                        .IsUnique();

                    b.HasIndex(new[] { "ActivityCode" }, "activity_rules_activity_id_key")
                        .IsUnique();

                    b.ToTable("activity_rules", (string)null);
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Auth.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("identity_user_id");

                    b.Property<string>("ProfileCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_code");

                    b.Property<string>("ReasonRevoked")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reason_revoked");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("revoked_by_ip");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<string>("UvaCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uva_code");

                    b.HasKey("Id")
                        .HasName("refresh_tokens_pkey");

                    b.HasIndex("IdentityUserId");

                    b.HasIndex("ProfileCode");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UvaCode")
                        .IsUnique();

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Auth.UserSecurityAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DeviceFingerprint")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("device_fingerprint");

                    b.Property<bool>("IsTrusted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_trusted");

                    b.Property<DateTime?>("LastCodeSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_code_sent_at");

                    b.Property<string>("LastIpAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_ip_address");

                    b.Property<string>("ProfileCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UvaCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uva_code");

                    b.HasKey("Id")
                        .HasName("user_security_audits_pkey");

                    b.HasIndex("ProfileCode");

                    b.HasIndex("UvaCode")
                        .IsUnique();

                    b.HasIndex("ProfileCode", "DeviceFingerprint")
                        .IsUnique();

                    b.ToTable("user_security_audits", (string)null);
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Contract.RoleRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DurationInMonths")
                        .HasColumnType("integer")
                        .HasColumnName("duration_in_months");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("RequestedRoleId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("requested_role_id");

                    b.Property<string>("RequesterProfileCode")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("requester_profile_code");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResolvedByProfileCode")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("resolved_by_profile_code");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("stage-1")
                        .HasColumnName("state_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UvaCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uva_code");

                    b.HasKey("Id")
                        .HasName("role_requests_pkey");

                    b.HasIndex("RequestedRoleId");

                    b.HasIndex("RequesterProfileCode");

                    b.HasIndex("ResolvedByProfileCode");

                    b.HasIndex("UvaCode")
                        .IsUnique();

                    b.ToTable("role_requests", (string)null);
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Contract.UserScholarship", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AssignedProfileCode")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("assigned_profile_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("EvaluatorProfileCode")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("evaluator_profile_code");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<decimal>("RequiredHours")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("required_hours")
                        .HasDefaultValueSql("100.00");

                    b.Property<string>("ScholarshipTypeCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scholarship_type_code");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("stage-1")
                        .HasColumnName("state_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UvaCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uva_code");

                    b.HasKey("Id")
                        .HasName("user_scholarships_pkey");

                    b.HasIndex("AssignedProfileCode");

                    b.HasIndex("EvaluatorProfileCode");

                    b.HasIndex("UvaCode")
                        .IsUnique();

                    b.ToTable("user_scholarships", (string)null);
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Enrollment.Enrollment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActivityCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("activity_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EnrolledProfileCode")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("enrolled_profile_code");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("stage-1")
                        .HasColumnName("state_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UvaCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uva_code");

                    b.HasKey("Id")
                        .HasName("enrollments_pkey");

                    b.HasIndex("ActivityCode");

                    b.HasIndex("EnrolledProfileCode");

                    b.HasIndex("UvaCode")
                        .IsUnique();

                    b.ToTable("enrollments", (string)null);
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Enrollment.GroupEnrollment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActivityGroupCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("activity_group_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EnrollmentCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("enrollment_code");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("stage-1")
                        .HasColumnName("state_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UvaCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uva_code");

                    b.HasKey("Id")
                        .HasName("group_enrollment_pkey");

                    b.HasIndex("ActivityGroupCode");

                    b.HasIndex("EnrollmentCode");

                    b.HasIndex("UvaCode")
                        .IsUnique();

                    b.ToTable("group_enrollment", (string)null);
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Profile.MvActivityAnalytic", b =>
                {
                    b.Property<string>("ActivityCode")
                        .HasColumnType("text")
                        .HasColumnName("activity_code");

                    b.Property<string>("ActivityName")
                        .HasColumnType("text")
                        .HasColumnName("activity_name");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("ProgramCode")
                        .HasColumnType("text")
                        .HasColumnName("program_code");

                    b.Property<string>("ProgramName")
                        .HasColumnType("text")
                        .HasColumnName("program_name");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<decimal?>("TotalActivityHours")
                        .HasColumnType("numeric")
                        .HasColumnName("total_activity_hours");

                    b.Property<long?>("TotalAttended")
                        .HasColumnType("bigint")
                        .HasColumnName("total_attended");

                    b.Property<int?>("TotalCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("total_capacity");

                    b.Property<long?>("TotalEnrolled")
                        .HasColumnType("bigint")
                        .HasColumnName("total_enrolled");

                    b.ToTable((string)null);

                    b.ToView("mv_activity_analytics", (string)null);
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Profile.MvProgramAnalytic", b =>
                {
                    b.Property<string>("ProgramCode")
                        .HasColumnType("text")
                        .HasColumnName("program_code");

                    b.Property<string>("ProgramName")
                        .HasColumnType("text")
                        .HasColumnName("program_name");

                    b.Property<long?>("TotalActivities")
                        .HasColumnType("bigint")
                        .HasColumnName("total_activities");

                    b.Property<decimal?>("TotalGeneratedHours")
                        .HasColumnType("numeric")
                        .HasColumnName("total_generated_hours");

                    b.Property<long?>("TotalUniqueVolunteers")
                        .HasColumnType("bigint")
                        .HasColumnName("total_unique_volunteers");

                    b.ToTable((string)null);

                    b.ToView("mv_program_analytics", (string)null);
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Profile.MvScholarshipPerformance", b =>
                {
                    b.Property<decimal?>("CompletedHours")
                        .HasColumnType("numeric")
                        .HasColumnName("completed_hours");

                    b.Property<decimal?>("CompletionPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("completion_percentage");

                    b.Property<string>("ContractState")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contract_state");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("ProfileCode")
                        .HasColumnType("text")
                        .HasColumnName("profile_code");

                    b.Property<decimal?>("RemainingHours")
                        .HasColumnType("numeric")
                        .HasColumnName("remaining_hours");

                    b.Property<decimal?>("RequiredHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("required_hours");

                    b.Property<string>("ScholarshipCode")
                        .HasColumnType("text")
                        .HasColumnName("scholarship_code");

                    b.Property<string>("ScholarshipType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("scholarship_type");

                    b.ToTable((string)null);

                    b.ToView("mv_scholarship_performance", (string)null);
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Profile.MvVolunteerHistory", b =>
                {
                    b.Property<string>("CareerName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("career_name");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<DateTime?>("LastActivityDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_date");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<decimal?>("PersonalGoalHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("personal_goal_hours");

                    b.Property<string>("ProfileCode")
                        .HasColumnType("text")
                        .HasColumnName("profile_code");

                    b.Property<long?>("TotalActivitiesParticipated")
                        .HasColumnType("bigint")
                        .HasColumnName("total_activities_participated");

                    b.Property<decimal?>("TotalLoggedHours")
                        .HasColumnType("numeric")
                        .HasColumnName("total_logged_hours");

                    b.Property<decimal?>("ValidatedHours")
                        .HasColumnType("numeric")
                        .HasColumnName("validated_hours");

                    b.ToTable((string)null);

                    b.ToView("mv_volunteer_history", (string)null);
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Profile.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLocation")
                        .HasColumnType("text")
                        .HasColumnName("address_location");

                    b.Property<string>("CareerCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("career_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("identity_user_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<decimal>("PersonalGoalHours")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("personal_goal_hours")
                        .HasDefaultValueSql("0.00");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("stage-1")
                        .HasColumnName("state_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UvaCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uva_code");

                    b.HasKey("Id")
                        .HasName("profiles_pkey");

                    b.HasIndex("IdentityUserId")
                        .IsUnique();

                    b.HasIndex("UvaCode")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "profiles_email_key")
                        .IsUnique();

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Tracking.Evidence", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EvidenceTypeCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("evidence_type_code");

                    b.Property<double>("LocationLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("location_latitude");

                    b.Property<double>("LocationLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("location_longitude");

                    b.Property<string>("Observations")
                        .HasColumnType("text")
                        .HasColumnName("observations");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<string>("TrackingLogCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tracking_log_code");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UvaCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uva_code");

                    b.HasKey("Id")
                        .HasName("evidences_pkey");

                    b.HasIndex("TrackingLogCode");

                    b.HasIndex("UvaCode")
                        .IsUnique();

                    b.ToTable("evidences", (string)null);
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Tracking.TrackingLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("CalculatedHours")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("calculated_hours")
                        .HasDefaultValueSql("0.00");

                    b.Property<string>("CheckInRegisteredByCode")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("check_in_registered_by_code");

                    b.Property<string>("CheckOutRegisteredByCode")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("check_out_registered_by_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EnrollmentCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("enrollment_code");

                    b.Property<DateTime?>("EntryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entry_time");

                    b.Property<DateTime?>("ExitTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exit_time");

                    b.Property<string>("GroupEnrollmentCode")
                        .HasColumnType("text")
                        .HasColumnName("group_enrollment_code");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("stage-1")
                        .HasColumnName("state_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UvaCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uva_code");

                    b.HasKey("Id")
                        .HasName("tracking_logs_pkey");

                    b.HasIndex("CheckInRegisteredByCode");

                    b.HasIndex("CheckOutRegisteredByCode");

                    b.HasIndex("EnrollmentCode");

                    b.HasIndex("GroupEnrollmentCode");

                    b.HasIndex("UvaCode")
                        .IsUnique();

                    b.ToTable("tracking_logs", (string)null);
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.VolProgram.VolProgram", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Acronym")
                        .HasColumnType("text")
                        .HasColumnName("acronym");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ManagerProfileCode")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("manager_profile_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("stage-1")
                        .HasColumnName("state_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UvaCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uva_code");

                    b.HasKey("Id")
                        .HasName("vol_programs_pkey");

                    b.HasIndex("ManagerProfileCode");

                    b.HasIndex("UvaCode")
                        .IsUnique();

                    b.ToTable("vol_programs", (string)null);
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.VolProgram.VolProgramCollaborator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AssignedByProfileCode")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("assigned_by_profile_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ProfileCode")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("profile_code");

                    b.Property<string>("ProgramCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("program_code");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("stage-1")
                        .HasColumnName("state_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UvaCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uva_code");

                    b.HasKey("Id")
                        .HasName("vol_program_collaborators_pkey");

                    b.HasIndex("AssignedByProfileCode");

                    b.HasIndex("ProfileCode");

                    b.HasIndex("ProgramCode");

                    b.HasIndex("UvaCode")
                        .IsUnique();

                    b.ToTable("vol_program_collaborators", (string)null);
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.VolProgram.VolProgramContent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActivitiesDescription")
                        .HasColumnType("text")
                        .HasColumnName("activities_description");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("text")
                        .HasColumnName("contact_info");

                    b.Property<string>("CoverPhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("cover_photo_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("LeadershipInfo")
                        .HasColumnType("text")
                        .HasColumnName("leadership_info");

                    b.Property<string>("MissionStatement")
                        .HasColumnType("text")
                        .HasColumnName("mission_statement");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("profile_photo_url");

                    b.Property<string>("ProgramCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("program_code");

                    b.Property<string>("ScheduleInfo")
                        .HasColumnType("text")
                        .HasColumnName("schedule_info");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UvaCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uva_code");

                    b.HasKey("Id")
                        .HasName("vol_program_contents_pkey");

                    b.HasIndex("UvaCode")
                        .IsUnique();

                    b.HasIndex(new[] { "ProgramCode" }, "program_content_program_id_key")
                        .IsUnique();

                    b.ToTable("vol_program_contents", (string)null);
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.VolProgram.VolProgramPattern", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ProgramCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("program_code");

                    b.Property<string>("RecurrenceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("recurrence_type");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("stage-1")
                        .HasColumnName("state_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UvaCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uva_code");

                    b.HasKey("Id")
                        .HasName("vol_program_patterns_pkey");

                    b.HasIndex("ProgramCode");

                    b.HasIndex("UvaCode")
                        .IsUnique();

                    b.ToTable("vol_program_patterns", (string)null);
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.VolProgram.VolProgramPatternDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short?>("DayOfMonth")
                        .HasColumnType("smallint")
                        .HasColumnName("day_of_month");

                    b.Property<short?>("DayOfWeek")
                        .HasColumnType("smallint")
                        .HasColumnName("day_of_week");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<TimeOnly?>("EndHour")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_hour");

                    b.Property<TimeOnly?>("StartHour")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_hour");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("stage-1")
                        .HasColumnName("state_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UvaCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uva_code");

                    b.Property<string>("VolProgramPatternCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vol_program_pattern_code");

                    b.Property<short?>("WeekOfMonth")
                        .HasColumnType("smallint")
                        .HasColumnName("week_of_month");

                    b.HasKey("Id")
                        .HasName("vol_program_pattern_details_pkey");

                    b.HasIndex("UvaCode")
                        .IsUnique();

                    b.HasIndex("VolProgramPatternCode");

                    b.ToTable("vol_program_pattern_details", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Activity.Activity", b =>
                {
                    b.HasOne("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.VolProgram.VolProgram", "Program")
                        .WithMany("Activities")
                        .HasForeignKey("ProgramCode")
                        .HasPrincipalKey("UvaCode")
                        .IsRequired()
                        .HasConstraintName("activities_program_id_fkey");

                    b.HasOne("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Profile.Profile", "ResponsibleProfile")
                        .WithMany("Activities")
                        .HasForeignKey("ResponsibleProfileCode")
                        .HasPrincipalKey("UvaCode")
                        .HasConstraintName("activities_responsible_profile_id_fkey");

                    b.HasOne("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.VolProgram.VolProgramPattern", "VolProgramPattern")
                        .WithMany("Activities")
                        .HasForeignKey("VolProgramPatternCode")
                        .HasPrincipalKey("UvaCode")
                        .HasConstraintName("activities_vol_program_pattern_id_fkey");

                    b.Navigation("Program");

                    b.Navigation("ResponsibleProfile");

                    b.Navigation("VolProgramPattern");
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Activity.ActivityGroup", b =>
                {
                    b.HasOne("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Activity.Activity", "Activity")
                        .WithMany("ActivityGroups")
                        .HasForeignKey("ActivityCode")
                        .HasPrincipalKey("UvaCode")
                        .IsRequired()
                        .HasConstraintName("activity_group_activity_id_fkey");

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Activity.ActivityRule", b =>
                {
                    b.HasOne("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Activity.Activity", "Activity")
                        .WithOne("ActivityRule")
                        .HasForeignKey("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Activity.ActivityRule", "ActivityCode")
                        .HasPrincipalKey("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Activity.Activity", "UvaCode")
                        .IsRequired()
                        .HasConstraintName("activity_rules_activity_id_fkey");

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Auth.UserSecurityAudit", b =>
                {
                    b.HasOne("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Profile.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileCode")
                        .HasPrincipalKey("UvaCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_security_audits_profile_id_fkey");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Contract.RoleRequest", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", "RequestedRole")
                        .WithMany()
                        .HasForeignKey("RequestedRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("role_requests_requested_role_id_fkey");

                    b.HasOne("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Profile.Profile", "RequesterProfile")
                        .WithMany("RoleRequestRequesterProfiles")
                        .HasForeignKey("RequesterProfileCode")
                        .HasPrincipalKey("UvaCode")
                        .IsRequired()
                        .HasConstraintName("role_requests_requester_profile_id_fkey");

                    b.HasOne("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Profile.Profile", "ResolvedByProfile")
                        .WithMany("RoleRequestResolvedByProfiles")
                        .HasForeignKey("ResolvedByProfileCode")
                        .HasPrincipalKey("UvaCode")
                        .HasConstraintName("role_requests_resolved_by_profile_id_fkey");

                    b.Navigation("RequestedRole");

                    b.Navigation("RequesterProfile");

                    b.Navigation("ResolvedByProfile");
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Contract.UserScholarship", b =>
                {
                    b.HasOne("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Profile.Profile", "AssignedProfile")
                        .WithMany("UserScholarshipAssignedProfiles")
                        .HasForeignKey("AssignedProfileCode")
                        .HasPrincipalKey("UvaCode")
                        .IsRequired()
                        .HasConstraintName("user_scholarships_assigned_profile_id_fkey");

                    b.HasOne("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Profile.Profile", "EvaluatorProfile")
                        .WithMany("UserScholarshipEvaluatorProfiles")
                        .HasForeignKey("EvaluatorProfileCode")
                        .HasPrincipalKey("UvaCode")
                        .HasConstraintName("user_scholarships_evaluator_profile_id_fkey");

                    b.Navigation("AssignedProfile");

                    b.Navigation("EvaluatorProfile");
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Enrollment.Enrollment", b =>
                {
                    b.HasOne("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Activity.Activity", "Activity")
                        .WithMany("Enrollments")
                        .HasForeignKey("ActivityCode")
                        .HasPrincipalKey("UvaCode")
                        .IsRequired()
                        .HasConstraintName("enrollments_activity_id_fkey");

                    b.HasOne("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Profile.Profile", "EnrolledProfile")
                        .WithMany("Enrollments")
                        .HasForeignKey("EnrolledProfileCode")
                        .HasPrincipalKey("UvaCode")
                        .IsRequired()
                        .HasConstraintName("enrollments_enrolled_profile_id_fkey");

                    b.Navigation("Activity");

                    b.Navigation("EnrolledProfile");
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Enrollment.GroupEnrollment", b =>
                {
                    b.HasOne("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Activity.ActivityGroup", "ActivityGroup")
                        .WithMany("GroupEnrollments")
                        .HasForeignKey("ActivityGroupCode")
                        .HasPrincipalKey("UvaCode")
                        .IsRequired()
                        .HasConstraintName("group_enrollment_activity_group_id_fkey");

                    b.HasOne("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Enrollment.Enrollment", "Enrollment")
                        .WithMany("GroupEnrollments")
                        .HasForeignKey("EnrollmentCode")
                        .HasPrincipalKey("UvaCode")
                        .IsRequired()
                        .HasConstraintName("group_enrollment_enrollment_id_fkey");

                    b.Navigation("ActivityGroup");

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Profile.Profile", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithOne()
                        .HasForeignKey("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Profile.Profile", "IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("profiles_identity_user_id_fkey");

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Tracking.Evidence", b =>
                {
                    b.HasOne("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Tracking.TrackingLog", "TrackingLog")
                        .WithMany("Evidences")
                        .HasForeignKey("TrackingLogCode")
                        .HasPrincipalKey("UvaCode")
                        .IsRequired()
                        .HasConstraintName("evidences_tracking_log_id_fkey");

                    b.Navigation("TrackingLog");
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Tracking.TrackingLog", b =>
                {
                    b.HasOne("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Profile.Profile", "CheckInRegisteredBy")
                        .WithMany("TrackingLogCheckInRegisteredBies")
                        .HasForeignKey("CheckInRegisteredByCode")
                        .HasPrincipalKey("UvaCode")
                        .HasConstraintName("tracking_logs_check_in_registered_by_id_fkey");

                    b.HasOne("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Profile.Profile", "CheckOutRegisteredBy")
                        .WithMany("TrackingLogCheckOutRegisteredBies")
                        .HasForeignKey("CheckOutRegisteredByCode")
                        .HasPrincipalKey("UvaCode")
                        .HasConstraintName("tracking_logs_check_out_registered_by_id_fkey");

                    b.HasOne("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Enrollment.Enrollment", "Enrollment")
                        .WithMany("TrackingLogs")
                        .HasForeignKey("EnrollmentCode")
                        .HasPrincipalKey("UvaCode")
                        .IsRequired()
                        .HasConstraintName("tracking_logs_enrollment_id_fkey");

                    b.HasOne("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Enrollment.GroupEnrollment", "GroupEnrollment")
                        .WithMany("TrackingLogs")
                        .HasForeignKey("GroupEnrollmentCode")
                        .HasPrincipalKey("UvaCode")
                        .HasConstraintName("tracking_logs_group_enrollment_id_fkey");

                    b.Navigation("CheckInRegisteredBy");

                    b.Navigation("CheckOutRegisteredBy");

                    b.Navigation("Enrollment");

                    b.Navigation("GroupEnrollment");
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.VolProgram.VolProgram", b =>
                {
                    b.HasOne("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Profile.Profile", "ManagerProfile")
                        .WithMany("VolPrograms")
                        .HasForeignKey("ManagerProfileCode")
                        .HasPrincipalKey("UvaCode")
                        .HasConstraintName("vol_programs_manager_profile_id_fkey");

                    b.Navigation("ManagerProfile");
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.VolProgram.VolProgramCollaborator", b =>
                {
                    b.HasOne("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Profile.Profile", "AssignedByProfile")
                        .WithMany("VolProgramCollaboratorAssignedByProfiles")
                        .HasForeignKey("AssignedByProfileCode")
                        .HasPrincipalKey("UvaCode")
                        .HasConstraintName("vol_program_collaborators_assigned_by_profile_id_fkey");

                    b.HasOne("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Profile.Profile", "Profile")
                        .WithMany("VolProgramCollaboratorProfiles")
                        .HasForeignKey("ProfileCode")
                        .HasPrincipalKey("UvaCode")
                        .IsRequired()
                        .HasConstraintName("vol_program_collaborators_profile_id_fkey");

                    b.HasOne("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.VolProgram.VolProgram", "Program")
                        .WithMany("VolProgramCollaborators")
                        .HasForeignKey("ProgramCode")
                        .HasPrincipalKey("UvaCode")
                        .IsRequired()
                        .HasConstraintName("vol_program_collaborators_program_id_fkey");

                    b.Navigation("AssignedByProfile");

                    b.Navigation("Profile");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.VolProgram.VolProgramContent", b =>
                {
                    b.HasOne("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.VolProgram.VolProgram", "Program")
                        .WithOne("VolProgramContent")
                        .HasForeignKey("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.VolProgram.VolProgramContent", "ProgramCode")
                        .HasPrincipalKey("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.VolProgram.VolProgram", "UvaCode")
                        .IsRequired()
                        .HasConstraintName("vol_program_contents_program_id_fkey");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.VolProgram.VolProgramPattern", b =>
                {
                    b.HasOne("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.VolProgram.VolProgram", "Program")
                        .WithMany("VolProgramPatterns")
                        .HasForeignKey("ProgramCode")
                        .HasPrincipalKey("UvaCode")
                        .IsRequired()
                        .HasConstraintName("vol_program_patterns_program_id_fkey");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.VolProgram.VolProgramPatternDetail", b =>
                {
                    b.HasOne("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.VolProgram.VolProgramPattern", "VolProgramPattern")
                        .WithMany("VolProgramPatternDetails")
                        .HasForeignKey("VolProgramPatternCode")
                        .HasPrincipalKey("UvaCode")
                        .IsRequired()
                        .HasConstraintName("vol_program_pattern_details_vol_program_pattern_id_fkey");

                    b.Navigation("VolProgramPattern");
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Activity.Activity", b =>
                {
                    b.Navigation("ActivityGroups");

                    b.Navigation("ActivityRule");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Activity.ActivityGroup", b =>
                {
                    b.Navigation("GroupEnrollments");
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Enrollment.Enrollment", b =>
                {
                    b.Navigation("GroupEnrollments");

                    b.Navigation("TrackingLogs");
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Enrollment.GroupEnrollment", b =>
                {
                    b.Navigation("TrackingLogs");
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Profile.Profile", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Enrollments");

                    b.Navigation("RoleRequestRequesterProfiles");

                    b.Navigation("RoleRequestResolvedByProfiles");

                    b.Navigation("TrackingLogCheckInRegisteredBies");

                    b.Navigation("TrackingLogCheckOutRegisteredBies");

                    b.Navigation("UserScholarshipAssignedProfiles");

                    b.Navigation("UserScholarshipEvaluatorProfiles");

                    b.Navigation("VolProgramCollaboratorAssignedByProfiles");

                    b.Navigation("VolProgramCollaboratorProfiles");

                    b.Navigation("VolPrograms");
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.Tracking.TrackingLog", b =>
                {
                    b.Navigation("Evidences");
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.VolProgram.VolProgram", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("VolProgramCollaborators");

                    b.Navigation("VolProgramContent");

                    b.Navigation("VolProgramPatterns");
                });

            modelBuilder.Entity("U_VoluntApp_Core.Src.Infrastructure.Persistence.Models.VolProgram.VolProgramPattern", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("VolProgramPatternDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
