-- BUSINESS TABLES SCHEMA (WITHOUT IDENTITY REFERENCES)
-- This version removes all FK references to AspNetUsers for initial scaffolding

-- States
CREATE TABLE public.profile_state ( 
    id SERIAL PRIMARY KEY, 
    uva_code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL UNIQUE 
);

CREATE TABLE public.program_state ( 
    id SERIAL PRIMARY KEY, 
    uva_code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL UNIQUE 
);

CREATE TABLE public.activity_state ( 
    id SERIAL PRIMARY KEY, 
    uva_code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL UNIQUE 
);

CREATE TABLE public.enrollment_state ( 
    id SERIAL PRIMARY KEY, 
    uva_code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL UNIQUE 
);

CREATE TABLE public.tracking_state ( 
    id SERIAL PRIMARY KEY, 
    uva_code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL UNIQUE 
);

CREATE TABLE public.contract_state ( 
    id SERIAL PRIMARY KEY, 
    uva_code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL UNIQUE 
);

CREATE TABLE public.role_request_state ( 
    id SERIAL PRIMARY KEY, 
    uva_code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL UNIQUE 
);

-- Types
CREATE TABLE public.activity_type ( 
    id SERIAL PRIMARY KEY, 
    uva_code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL UNIQUE,
    is_active BOOLEAN DEFAULT true NOT NULL
);

CREATE TABLE public.evidence_type ( 
    id SERIAL PRIMARY KEY, 
    uva_code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL UNIQUE,
    is_active BOOLEAN DEFAULT true NOT NULL
);

CREATE TABLE public.tracking_type ( 
    id SERIAL PRIMARY KEY, 
    uva_code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL UNIQUE,
    is_active BOOLEAN DEFAULT true NOT NULL
);

CREATE TABLE public.career_type ( 
    id SERIAL PRIMARY KEY, 
    uva_code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL UNIQUE, 
    is_active BOOLEAN DEFAULT true NOT NULL
);

CREATE TABLE public.scholarship_type ( 
    id SERIAL PRIMARY KEY, 
    uva_code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL UNIQUE,
    is_active BOOLEAN DEFAULT true NOT NULL
);

-- Tables (WITHOUT AspNetUsers FK for now)
CREATE TABLE public.profiles (
    id SERIAL PRIMARY KEY,
    identity_user_id VARCHAR(450) NOT NULL,
    uva_code VARCHAR(100) NOT NULL UNIQUE,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    photo_url TEXT,
    career_code VARCHAR(100) REFERENCES public.career_type(uva_code),
    address_location TEXT,
    phone TEXT,
    personal_goal_hours NUMERIC(5,2) DEFAULT 0.00 NOT NULL,
    state_code VARCHAR(100) DEFAULT 'stage-1' REFERENCES public.profile_state(uva_code) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);
CREATE INDEX idx_profiles_uva_code ON public.profiles(uva_code);

CREATE TABLE public.vol_programs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uva_code VARCHAR(100) NOT NULL UNIQUE,
    name TEXT NOT NULL,
    acronym TEXT,
    manager_profile_code VARCHAR(100) REFERENCES public.profiles(uva_code),
    state_code VARCHAR(100) DEFAULT 'stage-1' REFERENCES public.program_state(uva_code) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);
CREATE INDEX idx_vol_programs_uva_code ON public.vol_programs(uva_code);

CREATE TABLE public.program_content (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uva_code VARCHAR(100) NOT NULL UNIQUE,
    program_code VARCHAR(100) UNIQUE NOT NULL REFERENCES public.vol_programs(uva_code),
    description TEXT,
    activities_description TEXT,
    schedule_info TEXT,
    leadership_info TEXT,
    contact_info TEXT,
    mission_statement TEXT,
    profile_photo_url TEXT,
    cover_photo_url TEXT,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ
);
CREATE INDEX idx_program_content_uva_code ON public.program_content(uva_code);

CREATE TABLE public.program_collaborators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uva_code VARCHAR(100) NOT NULL UNIQUE,
    program_code VARCHAR(100) REFERENCES public.vol_programs(uva_code) NOT NULL,
    profile_code VARCHAR(100) REFERENCES public.profiles(uva_code) NOT NULL,
    assigned_by_profile_code VARCHAR(100) REFERENCES public.profiles(uva_code),
    state_code VARCHAR(100) DEFAULT 'stage-1' REFERENCES public.contract_state(uva_code) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);
CREATE INDEX idx_program_collaborators_uva_code ON public.program_collaborators(uva_code);

CREATE TABLE public.activity_recurrence_patterns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uva_code VARCHAR(100) NOT NULL UNIQUE,
    program_code VARCHAR(100) REFERENCES public.vol_programs(uva_code) NOT NULL,
    name TEXT NOT NULL,
    recurrence_type VARCHAR(20) NOT NULL,
    state_code VARCHAR(100) DEFAULT 'stage-1' REFERENCES public.activity_state(uva_code) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);
CREATE INDEX idx_activity_recurrence_patterns_uva_code ON public.activity_recurrence_patterns(uva_code);

CREATE TABLE public.activity_recurrence_detail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uva_code VARCHAR(100) NOT NULL UNIQUE,
    activity_recurrence_pattern_code VARCHAR(100) REFERENCES public.activity_recurrence_patterns(uva_code) NOT NULL,
    day_of_week SMALLINT,
    day_of_month SMALLINT,
    week_of_month SMALLINT,
    start_hour TIME,
    end_hour TIME,
    state_code VARCHAR(100) DEFAULT 'stage-1' REFERENCES public.activity_state(uva_code) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);
CREATE INDEX idx_activity_recurrence_detail_uva_code ON public.activity_recurrence_detail(uva_code);

CREATE TABLE public.activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uva_code VARCHAR(100) NOT NULL UNIQUE,
    program_code VARCHAR(100) REFERENCES public.vol_programs(uva_code) NOT NULL,
    responsible_profile_code VARCHAR(100) REFERENCES public.profiles(uva_code),
    activity_type_code VARCHAR(100) REFERENCES public.activity_type(uva_code) NOT NULL,
    activity_recurrence_pattern_code VARCHAR(100) REFERENCES public.activity_recurrence_patterns(uva_code),
    name TEXT NOT NULL,
    description TEXT,
    start_date TIMESTAMPTZ NOT NULL,
    end_date TIMESTAMPTZ NOT NULL,
    location_latitude DOUBLE PRECISION NOT NULL,
    location_longitude DOUBLE PRECISION NOT NULL,
    registration_radius_meters INT DEFAULT 50 NOT NULL,
    state_code VARCHAR(100) DEFAULT 'stage-1' REFERENCES public.activity_state(uva_code) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);
CREATE INDEX idx_activities_uva_code ON public.activities(uva_code);

CREATE TABLE public.activity_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uva_code VARCHAR(100) NOT NULL UNIQUE,
    activity_code VARCHAR(100) REFERENCES public.activities(uva_code) UNIQUE NOT NULL,
    requires_enrollment BOOLEAN DEFAULT true NOT NULL,
    enrollment_deadline TIMESTAMPTZ,
    requires_approval BOOLEAN DEFAULT false NOT NULL,
    total_capacity INT DEFAULT 0,
    cost_amount NUMERIC(10,2) DEFAULT 0.0 NOT NULL,
    counts_volunteer_hours BOOLEAN DEFAULT true NOT NULL,
    photo_url TEXT,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ
);
CREATE INDEX idx_activity_rules_uva_code ON public.activity_rules(uva_code);

CREATE TABLE public.enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uva_code VARCHAR(100) NOT NULL UNIQUE,
    activity_code VARCHAR(100) REFERENCES public.activities(uva_code) NOT NULL,
    enrolled_profile_code VARCHAR(100) REFERENCES public.profiles(uva_code) NOT NULL,
    state_code VARCHAR(100) DEFAULT 'stage-1' REFERENCES public.enrollment_state(uva_code) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);
CREATE INDEX idx_enrollments_uva_code ON public.enrollments(uva_code);

CREATE TABLE public.activity_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uva_code VARCHAR(100) NOT NULL UNIQUE,
    activity_code VARCHAR(100) REFERENCES public.activities(uva_code) NOT NULL,
    name TEXT NOT NULL,
    details TEXT,
    total_capacity INT DEFAULT 0,
    start_date TIMESTAMPTZ,
    end_date TIMESTAMPTZ,
    state_code VARCHAR(100) DEFAULT 'stage-1' REFERENCES public.activity_state(uva_code) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);
CREATE INDEX idx_activity_group_uva_code ON public.activity_group(uva_code);

CREATE TABLE public.group_enrollment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uva_code VARCHAR(100) NOT NULL UNIQUE,
    activity_group_code VARCHAR(100) REFERENCES public.activity_group(uva_code) NOT NULL,
    enrollment_code VARCHAR(100) REFERENCES public.enrollments(uva_code) NOT NULL,
    state_code VARCHAR(100) DEFAULT 'stage-1' REFERENCES public.activity_state(uva_code) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);
CREATE INDEX idx_group_enrollment_uva_code ON public.group_enrollment(uva_code);

CREATE TABLE public.tracking_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uva_code VARCHAR(100) NOT NULL UNIQUE,
    enrollment_code VARCHAR(100) REFERENCES public.enrollments(uva_code) NOT NULL,
    group_enrollment_code VARCHAR(100) REFERENCES public.group_enrollment(uva_code),
    entry_time TIMESTAMPTZ,
    exit_time TIMESTAMPTZ,
    calculated_hours NUMERIC(5,2) DEFAULT 0.00 NOT NULL,
    state_code VARCHAR(100) DEFAULT 'stage-1' REFERENCES public.tracking_state(uva_code) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    check_in_registered_by_code VARCHAR(100) REFERENCES public.profiles(uva_code),
    check_out_registered_by_code VARCHAR(100) REFERENCES public.profiles(uva_code)
);
CREATE INDEX idx_tracking_logs_uva_code ON public.tracking_logs(uva_code);

CREATE TABLE public.evidences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uva_code VARCHAR(100) NOT NULL UNIQUE,
    tracking_log_code VARCHAR(100) REFERENCES public.tracking_logs(uva_code) NOT NULL,
    photo_url TEXT NOT NULL,
    evidence_type_code VARCHAR(100) REFERENCES public.evidence_type(uva_code) NOT NULL,
    type_code VARCHAR(100) REFERENCES public.tracking_type(uva_code) NOT NULL,
    observations TEXT,
    location_latitude DOUBLE PRECISION NOT NULL,
    location_longitude DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);
CREATE INDEX idx_evidences_uva_code ON public.evidences(uva_code);

CREATE TABLE public.user_scholarships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uva_code VARCHAR(100) NOT NULL UNIQUE,
    assigned_profile_code VARCHAR(100) REFERENCES public.profiles(uva_code) NOT NULL,
    evaluator_profile_code VARCHAR(100) REFERENCES public.profiles(uva_code),
    scholarship_type_code VARCHAR(100) REFERENCES public.scholarship_type(uva_code) NOT NULL,
    reason TEXT NOT NULL,
    required_hours NUMERIC(5,2) DEFAULT 100.00 NOT NULL,
    start_date TIMESTAMPTZ DEFAULT now() NOT NULL,
    end_date TIMESTAMPTZ,
    state_code VARCHAR(100) DEFAULT 'stage-1' REFERENCES public.contract_state(uva_code) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);
CREATE INDEX idx_user_scholarships_uva_code ON public.user_scholarships(uva_code);

CREATE TABLE public.role_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uva_code VARCHAR(100) NOT NULL UNIQUE,
    requester_profile_code VARCHAR(100) REFERENCES public.profiles(uva_code) NOT NULL,
    requested_role_id VARCHAR(450) NOT NULL,
    reason TEXT NOT NULL,
    duration_in_months INT,
    state_code VARCHAR(100) DEFAULT 'stage-1' REFERENCES public.role_request_state(uva_code) NOT NULL,
    resolved_by_profile_code VARCHAR(100) REFERENCES public.profiles(uva_code),
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    resolved_at TIMESTAMPTZ
);
CREATE INDEX idx_role_requests_uva_code ON public.role_requests(uva_code);