-- U-VoluntApp Full Database Schema
-- Includes Identity, Business Tables, and Materialized Views

-- 1. EF Migrations History
CREATE TABLE IF NOT EXISTS public."__EFMigrationsHistory" (
    "MigrationId" VARCHAR(150) PRIMARY KEY,
    "ProductVersion" VARCHAR(32) NOT NULL
);

-- 2. ASP.NET Identity Tables
CREATE TABLE public."AspNetRoles" (
    "Id" VARCHAR(450) PRIMARY KEY,
    "Name" VARCHAR(256) UNIQUE,
    "NormalizedName" VARCHAR(256) UNIQUE,
    "ConcurrencyStamp" TEXT
);

CREATE TABLE public."AspNetUsers" (
    "Id" VARCHAR(450) PRIMARY KEY,
    "UserName" VARCHAR(256) UNIQUE NOT NULL,
    "NormalizedUserName" VARCHAR(256) UNIQUE,
    "Email" VARCHAR(256) UNIQUE,
    "NormalizedEmail" VARCHAR(256),
    "EmailConfirmed" BOOLEAN DEFAULT false NOT NULL,
    "PasswordHash" TEXT,
    "SecurityStamp" TEXT,
    "ConcurrencyStamp" TEXT,
    "PhoneNumber" TEXT,
    "PhoneNumberConfirmed" BOOLEAN DEFAULT false NOT NULL,
    "TwoFactorEnabled" BOOLEAN DEFAULT false NOT NULL,
    "LockoutEnd" TIMESTAMPTZ,
    "LockoutEnabled" BOOLEAN DEFAULT true NOT NULL,
    "AccessFailedCount" INT DEFAULT 0 NOT NULL
);

CREATE TABLE public."AspNetUserRoles" (
    "UserId" VARCHAR(450) NOT NULL REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE,
    "RoleId" VARCHAR(450) NOT NULL REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE,
    PRIMARY KEY ("UserId", "RoleId")
);

CREATE TABLE public."AspNetUserClaims" (
    "Id" SERIAL PRIMARY KEY,
    "UserId" VARCHAR(450) NOT NULL REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE,
    "ClaimType" TEXT,
    "ClaimValue" TEXT
);

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" VARCHAR(128) NOT NULL,
    "ProviderKey" VARCHAR(128) NOT NULL,
    "ProviderDisplayName" TEXT,
    "UserId" VARCHAR(450) NOT NULL REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE,
    PRIMARY KEY ("LoginProvider", "ProviderKey")
);

CREATE TABLE public."AspNetRoleClaims" (
    "Id" SERIAL PRIMARY KEY,
    "RoleId" VARCHAR(450) NOT NULL REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE,
    "ClaimType" TEXT,
    "ClaimValue" TEXT
);

CREATE TABLE public."AspNetUserTokens" (
    "UserId" VARCHAR(450) NOT NULL REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE,
    "LoginProvider" VARCHAR(128) NOT NULL,
    "Name" VARCHAR(128) NOT NULL,
    "Value" TEXT,
    PRIMARY KEY ("UserId", "LoginProvider", "Name")
);

CREATE TABLE public."RefreshTokens" (
    "Id" SERIAL PRIMARY KEY,
    "Token" TEXT NOT NULL,
    "JwtId" TEXT NOT NULL,
    "IsUsed" BOOLEAN NOT NULL,
    "IsRevoked" BOOLEAN NOT NULL,
    "AddedDate" TIMESTAMPTZ NOT NULL,
    "ExpiryDate" TIMESTAMPTZ NOT NULL,
    "UserId" VARCHAR(450) NOT NULL REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE
);

-- 3. Business Tables (Without state/type catalog tables)

CREATE TABLE public.profiles (
    id SERIAL PRIMARY KEY,
    identity_user_id VARCHAR(450) NOT NULL REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE,
    uva_code VARCHAR(50) NOT NULL UNIQUE,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    photo_url TEXT,
    career_code VARCHAR(50) NOT NULL, -- Enum backed
    address_location TEXT,
    phone TEXT,
    personal_goal_hours NUMERIC(5,2) DEFAULT 0.00 NOT NULL,
    state_code VARCHAR(50) DEFAULT 'stage-1' NOT NULL, -- Enum backed
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);
CREATE INDEX idx_profiles_uva_code ON public.profiles(uva_code);

CREATE TABLE public.vol_programs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uva_code VARCHAR(50) NOT NULL UNIQUE,
    name TEXT NOT NULL,
    acronym TEXT,
    manager_profile_code VARCHAR(50) REFERENCES public.profiles(uva_code),
    state_code VARCHAR(50) DEFAULT 'stage-1' NOT NULL, -- Enum backed
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);
CREATE INDEX idx_vol_programs_uva_code ON public.vol_programs(uva_code);

CREATE TABLE public.program_content (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uva_code VARCHAR(50) NOT NULL UNIQUE,
    program_code VARCHAR(50) UNIQUE NOT NULL REFERENCES public.vol_programs(uva_code) ON DELETE CASCADE,
    description TEXT,
    activities_description TEXT,
    schedule_info TEXT,
    leadership_info TEXT,
    contact_info TEXT,
    mission_statement TEXT,
    profile_photo_url TEXT,
    cover_photo_url TEXT,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ
);
CREATE INDEX idx_program_content_uva_code ON public.program_content(uva_code);

CREATE TABLE public.program_collaborators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uva_code VARCHAR(50) NOT NULL UNIQUE,
    program_code VARCHAR(50) REFERENCES public.vol_programs(uva_code) NOT NULL,
    profile_code VARCHAR(50) REFERENCES public.profiles(uva_code) NOT NULL,
    assigned_by_profile_code VARCHAR(50) REFERENCES public.profiles(uva_code),
    state_code VARCHAR(50) DEFAULT 'stage-1' NOT NULL, -- Enum backed
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);
CREATE INDEX idx_program_collaborators_uva_code ON public.program_collaborators(uva_code);

CREATE TABLE public.activity_recurrence_patterns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uva_code VARCHAR(50) NOT NULL UNIQUE,
    program_code VARCHAR(50) REFERENCES public.vol_programs(uva_code) NOT NULL,
    name TEXT NOT NULL,
    recurrence_type VARCHAR(20) NOT NULL,
    state_code VARCHAR(50) DEFAULT 'stage-1' NOT NULL, -- Enum backed
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);
CREATE INDEX idx_activity_recurrence_patterns_uva_code ON public.activity_recurrence_patterns(uva_code);

CREATE TABLE public.activity_recurrence_detail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uva_code VARCHAR(50) NOT NULL UNIQUE,
    activity_recurrence_pattern_code VARCHAR(50) REFERENCES public.activity_recurrence_patterns(uva_code) NOT NULL,
    day_of_week SMALLINT,
    day_of_month SMALLINT,
    week_of_month SMALLINT,
    start_hour TIME,
    end_hour TIME,
    state_code VARCHAR(50) DEFAULT 'stage-1' NOT NULL, -- Enum backed
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);
CREATE INDEX idx_activity_recurrence_detail_uva_code ON public.activity_recurrence_detail(uva_code);

CREATE TABLE public.activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uva_code VARCHAR(50) NOT NULL UNIQUE,
    program_code VARCHAR(50) REFERENCES public.vol_programs(uva_code) NOT NULL,
    responsible_profile_code VARCHAR(50) REFERENCES public.profiles(uva_code),
    activity_type_code VARCHAR(50) NOT NULL, -- Enum backed
    activity_recurrence_pattern_code VARCHAR(50) REFERENCES public.activity_recurrence_patterns(uva_code),
    name TEXT NOT NULL,
    description TEXT,
    start_date TIMESTAMPTZ NOT NULL,
    end_date TIMESTAMPTZ NOT NULL,
    location_latitude DOUBLE PRECISION NOT NULL,
    location_longitude DOUBLE PRECISION NOT NULL,
    registration_radius_meters INT DEFAULT 50 NOT NULL,
    state_code VARCHAR(50) DEFAULT 'stage-1' NOT NULL, -- Enum backed
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);
CREATE INDEX idx_activities_uva_code ON public.activities(uva_code);

CREATE TABLE public.activity_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uva_code VARCHAR(50) NOT NULL UNIQUE,
    activity_code VARCHAR(50) REFERENCES public.activities(uva_code) UNIQUE NOT NULL,
    requires_enrollment BOOLEAN DEFAULT true NOT NULL,
    enrollment_deadline TIMESTAMPTZ,
    requires_approval BOOLEAN DEFAULT false NOT NULL,
    total_capacity INT DEFAULT 0,
    cost_amount NUMERIC(10,2) DEFAULT 0.0 NOT NULL,
    counts_volunteer_hours BOOLEAN DEFAULT true NOT NULL,
    photo_url TEXT,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ
);
CREATE INDEX idx_activity_rules_uva_code ON public.activity_rules(uva_code);

CREATE TABLE public.enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uva_code VARCHAR(50) NOT NULL UNIQUE,
    activity_code VARCHAR(50) REFERENCES public.activities(uva_code) NOT NULL,
    enrolled_profile_code VARCHAR(50) REFERENCES public.profiles(uva_code) NOT NULL,
    state_code VARCHAR(50) DEFAULT 'stage-1' NOT NULL, -- Enum backed
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);
CREATE INDEX idx_enrollments_uva_code ON public.enrollments(uva_code);

CREATE TABLE public.activity_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uva_code VARCHAR(50) NOT NULL UNIQUE,
    activity_code VARCHAR(50) REFERENCES public.activities(uva_code) NOT NULL,
    name TEXT NOT NULL,
    details TEXT,
    total_capacity INT DEFAULT 0,
    start_date TIMESTAMPTZ,
    end_date TIMESTAMPTZ,
    state_code VARCHAR(50) DEFAULT 'stage-1' NOT NULL, -- Enum backed
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);
CREATE INDEX idx_activity_group_uva_code ON public.activity_group(uva_code);

CREATE TABLE public.group_enrollment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uva_code VARCHAR(50) NOT NULL UNIQUE,
    activity_group_code VARCHAR(50) REFERENCES public.activity_group(uva_code) NOT NULL,
    enrollment_code VARCHAR(50) REFERENCES public.enrollments(uva_code) NOT NULL,
    state_code VARCHAR(50) DEFAULT 'stage-1' NOT NULL, -- Enum backed
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);
CREATE INDEX idx_group_enrollment_uva_code ON public.group_enrollment(uva_code);

CREATE TABLE public.tracking_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uva_code VARCHAR(50) NOT NULL UNIQUE,
    enrollment_code VARCHAR(50) REFERENCES public.enrollments(uva_code) NOT NULL,
    group_enrollment_code VARCHAR(50) REFERENCES public.group_enrollment(uva_code),
    entry_time TIMESTAMPTZ,
    exit_time TIMESTAMPTZ,
    calculated_hours NUMERIC(5,2) DEFAULT 0.00 NOT NULL,
    state_code VARCHAR(50) DEFAULT 'stage-1' NOT NULL, -- Enum backed
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    check_in_registered_by_code VARCHAR(50) REFERENCES public.profiles(uva_code),
    check_out_registered_by_code VARCHAR(50) REFERENCES public.profiles(uva_code)
);
CREATE INDEX idx_tracking_logs_uva_code ON public.tracking_logs(uva_code);

CREATE TABLE public.evidences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uva_code VARCHAR(50) NOT NULL UNIQUE,
    tracking_log_code VARCHAR(50) REFERENCES public.tracking_logs(uva_code) NOT NULL,
    photo_url TEXT NOT NULL,
    evidence_type_code VARCHAR(50) NOT NULL, -- Enum backed
    type_code VARCHAR(50) NOT NULL, -- Enum backed
    observations TEXT,
    location_latitude DOUBLE PRECISION NOT NULL,
    location_longitude DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);
CREATE INDEX idx_evidences_uva_code ON public.evidences(uva_code);

CREATE TABLE public.user_scholarships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uva_code VARCHAR(50) NOT NULL UNIQUE,
    assigned_profile_code VARCHAR(50) REFERENCES public.profiles(uva_code) NOT NULL,
    evaluator_profile_code VARCHAR(50) REFERENCES public.profiles(uva_code),
    scholarship_type_code VARCHAR(50) NOT NULL, -- Enum backed
    reason TEXT NOT NULL,
    required_hours NUMERIC(5,2) DEFAULT 100.00 NOT NULL,
    start_date TIMESTAMPTZ DEFAULT now() NOT NULL,
    end_date TIMESTAMPTZ,
    state_code VARCHAR(50) DEFAULT 'stage-1' NOT NULL, -- Enum backed
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);
CREATE INDEX idx_user_scholarships_uva_code ON public.user_scholarships(uva_code);

CREATE TABLE public.role_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uva_code VARCHAR(50) NOT NULL UNIQUE,
    requester_profile_code VARCHAR(50) REFERENCES public.profiles(uva_code) NOT NULL,
    requested_role_id VARCHAR(450) NOT NULL,
    reason TEXT NOT NULL,
    duration_in_months INT,
    state_code VARCHAR(50) DEFAULT 'stage-1' NOT NULL, -- Enum backed
    resolved_by_profile_code VARCHAR(50) REFERENCES public.profiles(uva_code),
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    resolved_at TIMESTAMPTZ
);
CREATE INDEX idx_role_requests_uva_code ON public.role_requests(uva_code);

-- 4. Materialized Views

CREATE MATERIALIZED VIEW public.mv_scholarship_performance AS
SELECT 
    us.uva_code AS scholarship_code,
    p.uva_code AS profile_code,
    p.first_name,
    p.last_name,
    us.scholarship_type_code AS scholarship_type, -- Now uses code
    us.required_hours,
    COALESCE(SUM(tl.calculated_hours), 0) AS completed_hours,
    GREATEST(us.required_hours - COALESCE(SUM(tl.calculated_hours), 0), 0) AS remaining_hours,
    CASE 
        WHEN us.required_hours > 0 THEN ROUND((COALESCE(SUM(tl.calculated_hours), 0) / us.required_hours) * 100, 2) 
        ELSE 0 
    END AS completion_percentage,
    us.state_code AS contract_state, -- Now uses code
    us.end_date
FROM public.user_scholarships us
JOIN public.profiles p ON us.assigned_profile_code = p.uva_code
LEFT JOIN public.enrollments e ON p.uva_code = e.enrolled_profile_code
LEFT JOIN public.tracking_logs tl ON e.uva_code = tl.enrollment_code 
    AND tl.state_code = 'stage-2' -- 'active' in TrackingState
    AND tl.created_at >= us.start_date
    AND tl.deleted_at IS NULL
GROUP BY 
    p.uva_code, p.first_name, p.last_name, us.scholarship_type_code, us.required_hours, us.state_code, us.end_date, us.uva_code;

CREATE UNIQUE INDEX idx_mv_scholarship_perf_code ON public.mv_scholarship_performance(scholarship_code);

CREATE MATERIALIZED VIEW public.mv_program_analytics AS
WITH activity_hours AS (
    SELECT 
        a.program_code,
        SUM(tl.calculated_hours) AS total_hours
    FROM public.activities a
    LEFT JOIN public.enrollments e ON a.uva_code = e.activity_code 
        AND e.state_code = 'stage-2' -- 'active' in EnrollmentState
        AND e.deleted_at IS NULL
    LEFT JOIN public.tracking_logs tl ON e.uva_code = tl.enrollment_code 
        AND tl.state_code = 'stage-2' -- 'active' in TrackingState
        AND tl.deleted_at IS NULL
    WHERE a.deleted_at IS NULL
    GROUP BY a.program_code
),
volunteer_counts AS (
    SELECT 
        a.program_code,
        COUNT(DISTINCT e.enrolled_profile_code) AS total_unique_volunteers
    FROM public.activities a
    LEFT JOIN public.enrollments e ON a.uva_code = e.activity_code 
        AND e.state_code = 'stage-2'
        AND e.deleted_at IS NULL
    WHERE a.deleted_at IS NULL
    GROUP BY a.program_code
)
SELECT 
    p.uva_code AS program_code,
    p.name AS program_name,
    COUNT(DISTINCT a.uva_code) AS total_activities,
    COALESCE(vc.total_unique_volunteers, 0) AS total_unique_volunteers,
    COALESCE(ah.total_hours, 0) AS total_generated_hours
FROM public.vol_programs p
LEFT JOIN public.activities a ON p.uva_code = a.program_code AND a.deleted_at IS NULL
LEFT JOIN activity_hours ah ON p.uva_code = ah.program_code
LEFT JOIN volunteer_counts vc ON p.uva_code = vc.program_code
WHERE p.deleted_at IS NULL
GROUP BY 
    p.uva_code, p.name, ah.total_hours, vc.total_unique_volunteers;

CREATE UNIQUE INDEX idx_mv_program_analytics_code ON public.mv_program_analytics(program_code);

CREATE MATERIALIZED VIEW public.mv_activity_analytics AS
WITH enrollment_hours AS (
    SELECT 
        e.activity_code,
        COUNT(DISTINCT e.uva_code) AS total_enrolled,
        COUNT(DISTINCT CASE WHEN tl.uva_code IS NOT NULL THEN e.uva_code END) AS total_attended,
        SUM(tl.calculated_hours) AS total_activity_hours
    FROM public.enrollments e
    LEFT JOIN public.tracking_logs tl ON e.uva_code = tl.enrollment_code 
        AND tl.state_code = 'stage-2'
        AND tl.deleted_at IS NULL
    WHERE e.state_code = 'stage-2'
        AND e.deleted_at IS NULL
    GROUP BY e.activity_code
)
SELECT 
    a.uva_code AS activity_code,
    p.uva_code AS program_code,
    p.name AS program_name,
    a.name AS activity_name,
    a.start_date,
    a.end_date,
    COALESCE(ar.total_capacity, 0) AS total_capacity,
    COALESCE(eh.total_enrolled, 0) AS total_enrolled,
    COALESCE(eh.total_attended, 0) AS total_attended,
    COALESCE(eh.total_activity_hours, 0) AS total_activity_hours
FROM public.activities a
JOIN public.vol_programs p ON a.program_code = p.uva_code AND p.deleted_at IS NULL
LEFT JOIN public.activity_rules ar ON a.uva_code = ar.activity_code
LEFT JOIN enrollment_hours eh ON a.uva_code = eh.activity_code
WHERE a.deleted_at IS NULL;

CREATE UNIQUE INDEX idx_mv_activity_analytics_code ON public.mv_activity_analytics(activity_code);

CREATE MATERIALIZED VIEW public.mv_volunteer_history AS
SELECT 
    p.uva_code AS profile_code,
    p.first_name,
    p.last_name,
    p.career_code AS career_name, -- Now uses code
    p.personal_goal_hours,
    COUNT(DISTINCT e.activity_code) AS total_activities_participated,
    COALESCE(SUM(CASE WHEN tl.state_code = 'stage-2' THEN tl.calculated_hours ELSE 0 END), 0) AS validated_hours,
    COALESCE(SUM(CASE WHEN tl.state_code IN ('stage-2', 'stage-1') THEN tl.calculated_hours ELSE 0 END), 0) AS total_logged_hours,
    MAX(tl.created_at) AS last_activity_date
FROM public.profiles p
LEFT JOIN public.enrollments e ON p.uva_code = e.enrolled_profile_code 
    AND e.state_code = 'stage-2'
    AND e.deleted_at IS NULL
LEFT JOIN public.tracking_logs tl ON e.uva_code = tl.enrollment_code AND tl.deleted_at IS NULL
WHERE p.deleted_at IS NULL
GROUP BY 
    p.uva_code, p.first_name, p.last_name, p.career_code, p.personal_goal_hours;

CREATE UNIQUE INDEX idx_mv_volunteer_history_profile_code ON public.mv_volunteer_history(profile_code);
