-- IDENTITY TABLES
CREATE TABLE public."AspNetRoles" (
    "Id" VARCHAR(450) PRIMARY KEY,
    "Name" VARCHAR(256) UNIQUE,
    "NormalizedName" VARCHAR(256) UNIQUE,
    "ConcurrencyStamp" TEXT
);

CREATE TABLE public."AspNetUsers" (
    "Id" VARCHAR(450) PRIMARY KEY,
    "UserName" VARCHAR(256) UNIQUE NOT NULL,
    "NormalizedUserName" VARCHAR(256) UNIQUE,
    "Email" VARCHAR(256) UNIQUE,
    "NormalizedEmail" VARCHAR(256),
    "EmailConfirmed" BOOLEAN DEFAULT false NOT NULL,
    "PasswordHash" TEXT,
    "SecurityStamp" TEXT,
    "ConcurrencyStamp" TEXT,
    "PhoneNumber" TEXT,
    "PhoneNumberConfirmed" BOOLEAN DEFAULT false NOT NULL,
    "TwoFactorEnabled" BOOLEAN DEFAULT false NOT NULL,
    "LockoutEnd" TIMESTAMPTZ,
    "LockoutEnabled" BOOLEAN DEFAULT true NOT NULL,
    "AccessFailedCount" INT DEFAULT 0 NOT NULL
);

CREATE TABLE public."AspNetUserRoles" (
    "UserId" VARCHAR(450) NOT NULL REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE,
    "RoleId" VARCHAR(450) NOT NULL REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE,
    PRIMARY KEY ("UserId", "RoleId")
);

CREATE TABLE public."AspNetUserClaims" (
    "Id" SERIAL PRIMARY KEY,
    "UserId" VARCHAR(450) NOT NULL REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE,
    "ClaimType" TEXT,
    "ClaimValue" TEXT
);

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" VARCHAR(128) NOT NULL,
    "ProviderKey" VARCHAR(128) NOT NULL,
    "ProviderDisplayName" TEXT,
    "UserId" VARCHAR(450) NOT NULL REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE,
    PRIMARY KEY ("LoginProvider", "ProviderKey")
);

CREATE TABLE public."AspNetRoleClaims" (
    "Id" SERIAL PRIMARY KEY,
    "RoleId" VARCHAR(450) NOT NULL REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE,
    "ClaimType" TEXT,
    "ClaimValue" TEXT
);

CREATE TABLE public."AspNetUserTokens" (
    "UserId" VARCHAR(450) NOT NULL REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE,
    "LoginProvider" VARCHAR(128) NOT NULL,
    "Name" VARCHAR(128) NOT NULL,
    "Value" TEXT,
    PRIMARY KEY ("UserId", "LoginProvider", "Name")
);

-- Catalogs
CREATE TABLE public.catalog_careers ( 
    id SERIAL PRIMARY KEY, 
    name VARCHAR(50) NOT NULL UNIQUE 
);

CREATE TABLE public.catalog_scholarship_types ( 
    id SERIAL PRIMARY KEY, 
    name VARCHAR(50) NOT NULL UNIQUE 
);

-- States
CREATE TABLE public.profile_state ( 
    id SERIAL PRIMARY KEY, 
    name VARCHAR(50) NOT NULL UNIQUE 
);

CREATE TABLE public.program_state ( 
    id SERIAL PRIMARY KEY, 
    name VARCHAR(50) NOT NULL UNIQUE 
);

CREATE TABLE public.activity_state ( 
    id SERIAL PRIMARY KEY, 
    name VARCHAR(50) NOT NULL UNIQUE 
);

CREATE TABLE public.enrollment_state ( 
    id SERIAL PRIMARY KEY, 
    name VARCHAR(50) NOT NULL UNIQUE 
);

CREATE TABLE public.tracking_state ( 
    id SERIAL PRIMARY KEY, 
    name VARCHAR(50) NOT NULL UNIQUE 
);

CREATE TABLE public.contract_state ( 
    id SERIAL PRIMARY KEY, 
    name VARCHAR(50) NOT NULL UNIQUE 
);

CREATE TABLE public.role_request_state ( 
    id SERIAL PRIMARY KEY, 
    name VARCHAR(50) NOT NULL UNIQUE 
);

-- Types
CREATE TABLE public.activity_type ( 
    id SERIAL PRIMARY KEY, 
    name VARCHAR(50) NOT NULL UNIQUE 
);

CREATE TABLE public.evidence_type ( 
    id SERIAL PRIMARY KEY, 
    name VARCHAR(50) NOT NULL UNIQUE 
);

CREATE TABLE public.tracking_type ( 
    id SERIAL PRIMARY KEY, 
    name VARCHAR(50) NOT NULL UNIQUE 
);


-- Tables
CREATE TABLE public.profiles (
    identity_user_id VARCHAR(450) PRIMARY KEY REFERENCES public."AspNetUsers"("Id"),
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    photo_url TEXT,
    career_id INT REFERENCES public.catalog_careers(id),
    address_location TEXT,
    phone TEXT,
    personal_goal_hours NUMERIC(5,2) DEFAULT 0.00 NOT NULL,
    state_id INT DEFAULT 1 REFERENCES public.profile_state(id) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE public.vol_programs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    acronym TEXT,
    manager_profile_id VARCHAR(450) REFERENCES public.profiles(identity_user_id),
    state_id INT DEFAULT 1 REFERENCES public.program_state(id) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE public.program_content (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id BIGINT UNIQUE NOT NULL REFERENCES public.vol_programs(id),
    description TEXT,
    activities_description TEXT,
    schedule_info TEXT,
    leadership_info TEXT,
    contact_info TEXT,
    mission_statement TEXT,
    profile_photo_url TEXT,
    cover_photo_url TEXT,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ
);

CREATE TABLE public.program_collaborators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id BIGINT REFERENCES public.vol_programs(id) NOT NULL,
    profile_id VARCHAR(450) REFERENCES public.profiles(identity_user_id) NOT NULL,
    assigned_by_profile_id VARCHAR(450) REFERENCES public.profiles(identity_user_id),
    state_id INT DEFAULT 1 REFERENCES public.contract_state(id) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE public.activity_recurrence_patterns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id BIGINT REFERENCES public.vol_programs(id) NOT NULL,
    name TEXT NOT NULL,
    recurrence_type VARCHAR(20) NOT NULL,
    state_id INT DEFAULT 1 REFERENCES public.activity_state(id) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE public.activity_recurrence_detail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_recurrence_pattern_id BIGINT REFERENCES public.activity_recurrence_patterns(id) NOT NULL,
    day_of_week SMALLINT,
    day_of_month SMALLINT,
    week_of_month SMALLINT,
    start_hour TIME,
    end_hour TIME,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ
);

CREATE TABLE public.activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id BIGINT REFERENCES public.vol_programs(id) NOT NULL,
    responsible_profile_id VARCHAR(450) REFERENCES public.profiles(identity_user_id),
    activity_type_id INT REFERENCES public.activity_type(id) NOT NULL,
    activity_recurrence_pattern_id BIGINT REFERENCES public.activity_recurrence_patterns(id),
    name TEXT NOT NULL,
    description TEXT,
    start_date TIMESTAMPTZ NOT NULL,
    end_date TIMESTAMPTZ NOT NULL,
    location_latitude DOUBLE PRECISION NOT NULL,
    location_longitude DOUBLE PRECISION NOT NULL,
    registration_radius_meters INT DEFAULT 50 NOT NULL,
    state_id INT DEFAULT 1 REFERENCES public.activity_state(id) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE public.activity_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id BIGINT REFERENCES public.activities(id) UNIQUE NOT NULL,
    requires_enrollment BOOLEAN DEFAULT true NOT NULL,
    enrollment_deadline TIMESTAMPTZ,
    requires_approval BOOLEAN DEFAULT false NOT NULL,
    total_capacity INT DEFAULT 0,
    cost_amount NUMERIC(10,2) DEFAULT 0.0 NOT NULL,
    counts_volunteer_hours BOOLEAN DEFAULT true NOT NULL,
    photo_url TEXT,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ
);

CREATE TABLE public.enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id BIGINT REFERENCES public.activities(id) NOT NULL,
    enrolled_profile_id VARCHAR(450) REFERENCES public.profiles(identity_user_id) NOT NULL,
    state_id INT DEFAULT 1 REFERENCES public.enrollment_state(id) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE public.activity_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id BIGINT REFERENCES public.activities(id) NOT NULL,
    name TEXT NOT NULL,
    details TEXT,
    total_capacity INT DEFAULT 0,
    start_date TIMESTAMPTZ,
    end_date TIMESTAMPTZ,
    state_id INT DEFAULT 1 REFERENCES public.activity_state(id) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE public.group_enrollment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_group_id BIGINT REFERENCES public.activity_group(id) NOT NULL,
    enrollment_id BIGINT REFERENCES public.enrollments(id) NOT NULL,
    state_id INT DEFAULT 1 REFERENCES public.activity_state(id) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE public.tracking_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id BIGINT REFERENCES public.enrollments(id) NOT NULL,
    entry_time TIMESTAMPTZ,
    exit_time TIMESTAMPTZ,
    calculated_hours NUMERIC(5,2) DEFAULT 0.00 NOT NULL,
    state_id INT DEFAULT 1 REFERENCES public.tracking_state(id) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    check_in_registered_by_id VARCHAR(450) REFERENCES public.profiles(identity_user_id),
    check_out_registered_by_id VARCHAR(450) REFERENCES public.profiles(identity_user_id)
);

CREATE TABLE public.evidences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_log_id BIGINT REFERENCES public.tracking_logs(id) NOT NULL,
    photo_url TEXT NOT NULL,
    evidence_type_id INT REFERENCES public.evidence_type(id) NOT NULL,
    type_id INT REFERENCES public.tracking_type(id) NOT NULL,
    observations TEXT,
    location_latitude DOUBLE PRECISION NOT NULL,
    location_longitude DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE public.user_scholarships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assigned_profile_id VARCHAR(450) REFERENCES public.profiles(identity_user_id) NOT NULL,
    evaluator_profile_id VARCHAR(450) REFERENCES public.profiles(identity_user_id),
    scholarship_type_id INT REFERENCES public.catalog_scholarship_types(id) NOT NULL,
    reason TEXT NOT NULL,
    required_hours NUMERIC(5,2) DEFAULT 100.00 NOT NULL,
    start_date TIMESTAMPTZ DEFAULT now() NOT NULL,
    end_date TIMESTAMPTZ,
    state_id INT DEFAULT 1 REFERENCES public.contract_state(id) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE public.role_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_profile_id VARCHAR(450) REFERENCES public.profiles(identity_user_id) NOT NULL,
    requested_role_id VARCHAR(450) NOT NULL REFERENCES public."AspNetRoles"("Id"),
    reason TEXT NOT NULL,
    duration_in_months INT,
    state_id INT DEFAULT 1 REFERENCES public.role_request_state(id) NOT NULL,
    resolved_by_profile_id VARCHAR(450) REFERENCES public.profiles(identity_user_id),
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    resolved_at TIMESTAMPTZ
);
