name: Pipeline Develop (CI)

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

permissions:
  contents: read
  security-events: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 10.0.x

      - name: Restore and Build
        run: |
          dotnet restore U-VoluntApp_Backend.csproj
          dotnet build U-VoluntApp_Backend.csproj --configuration Release --no-restore

      - name: Run Unit Tests
        run: |
          dotnet test tests/tests.csproj --configuration Release --no-build --verbosity normal

      - name: Build Temporary Image for Scan
        run: |
          docker build -t uvoluntapp-backend:scan -f Dockerfile .

      - name: Security Scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'uvoluntapp-backend:scan'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
